tap "domq/gdb"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "unkontributors/unko"
tap "wez/wezterm"
brew "aom"
brew "bat"
brew "bc"
brew "berkeley-db", link: true
brew "glib"
brew "python@3.9"
brew "coreutils"
brew "deno"
brew "libidn2"
brew "emacs"
brew "icu4c"
brew "harfbuzz"
brew "gobject-introspection"
brew "libass"
brew "ffmpeg"
brew "pango"
brew "fontforge"
brew "fzf"
brew "gcc"
brew "gcc@11"
brew "gd"
brew "gh"
brew "llvm@12", link: true
brew "ghc"
brew "ghostscript"
brew "git"
brew "git-filter-repo"
brew "glow"
brew "gnu-sed"
brew "gnu-time"
brew "gnupg"
brew "qt@5"
brew "gnuplot"
brew "librsvg"
brew "graphviz"
brew "imagemagick"
brew "jq"
brew "libsixel"
brew "libvterm"
brew "llvm"
brew "luarocks"
brew "make"
brew "mas"
brew "multitime"
brew "neovim"
brew "nkf"
brew "node"
brew "pandoc"
brew "pass"
brew "poppler"
brew "qt"
brew "ripgrep"
brew "ruby"
brew "sha2"
brew "silicon"
brew "sl"
brew "socat"
brew "vim", args: ["HEAD"]
brew "zsh"
brew "zsh-completions"
brew "unkontributors/unko/super_unko"
cask "discord"
cask "docker"
cask "font-udev-gothic"
cask "google-chrome"
cask "hammerspoon"
cask "mactex-no-gui"
cask "slack"
cask "steam"
cask "ukelele"
cask "wezterm-nightly"
cask "wolfram-engine"
cask "zoom"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "RunCat", id: 1429033973
mas "Xcode", id: 497799835
