[[plugins]]
repo = 'Shougo/ddu.vim'
depends = ['denops.vim']
on_event = ['CursorHold']
hook_source = '''
call ddu#custom#patch_global({
    \ 'ui': 'ff',
    \ 'sources': [
		\ {'name': 'buffer'},
		\ {'name': 'mr'},
		\ {'name': 'file_rec', 'params': {}}
		\ ],
    \ 'sourceOptions': {
    	\ '_': {
    		\ 'matchers': ['matcher_fzf'],
    		\ },
    	\ },
    \ 'kindOptions': {
    	\ 'file': {
    		\ 'defaultAction': 'open',
    		\ },
    	\ }
    \ })

autocmd FileType ddu-ff call s:ddu_my_settings()
function! s:ddu_my_settings() abort
	nnoremap <buffer><silent> <CR>
		\ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
	nnoremap <buffer><silent> <Space>
		\ <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
	nnoremap <buffer><silent> i
		\ <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
	nnoremap <buffer><silent> p
		\ <Cmd>call ddu#ui#ff#do_action('preview')<CR>
	nnoremap <buffer><silent> q
		\ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
endfunction

autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
function! s:ddu_filter_my_settings() abort
	inoremap <buffer><silent> <CR>
		\ <Esc><Cmd>close<CR>
	nnoremap <buffer><silent> <CR>
		\ <Cmd>close<CR>
	nnoremap <buffer><silent> q
		\ <Cmd>close<CR>
endfunction
'''

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
on_source = 'ddu.vim'

# UI
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'

# sources
[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
depends = 'ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file'
depends = 'ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'kuuote/ddu-source-mr'
depends = 'mr.vim'
on_source = 'ddu.vim'

[[plugins]]
repo = 'lambdalisue/mr.vim'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'

#filters
[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
on_source = 'ddu.vim'

# [[plugins]]
# repo = 'Shougo/ddu-filter-matcher_substring'
# on_source = 'ddu.vim'

#kinds
[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'
