# Let dein manage dein
# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'vim-jp/vital.vim'
merged = false

[[plugins]]
repo = 'lambdalisue/vital-Whisky'
merged = false

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
set background=dark
colorscheme iceberg
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-denops/denops.vim'
rev = 'support-global-server'
hook_add = 'let g:denops_server_addr = "127.0.0.1:32123"'

[[plugins]]
repo = 'lambdalisue/guise.vim'
depends = 'denops.vim'
