[[plugins]]
repo = 'lervag/vimtex'
on_ft=['tex']
hook_source='''
let g:vimtex_view_general_viewer = 'displayline'
let g:vimtex_view_general_options = '-r @line @pdf @tex'
'''

[[plugins]]
repo = 'skanehira/preview-markdown.vim'
on_ft=['markdown']
hook_source='''
let g:preview_markdown_auto_update = 1
let g:preview_markdown_parser = "glow"
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_ft='help'
hook_add = 'set helplang=ja'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
hook_add = '''
" let g:quickrun_config = {}
'''

[[plugins]]
repo = 'skanehira/denops-translate.vim'
on_cmd = 'Translate'
# hook_add = 'let g:translate_popup_window = 0'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# [[plugins]]
# repo = 'cohama/lexima.vim'
# on_event = ['InsertEnter']

# [[plugins]]
# repo = 'vim-pandoc/vim-pandoc'
# on_ft = ['markdown']

### jupyter
[[plugins]]
repo = 'goerz/jupytext.vim'
on_path = '.*\.ipynb'
hook_add = '''
let g:jupytext_fmt = 'py:percent'
let g:jupytext_filetype_map = {'py': 'python'}
'''

[[plugins]]
repo = 'jpalardy/vim-slime'
on_source = 'jupytext.vim'
hook_add = '''
let g:slime_target = 'vimterminal'
let g:slime_vimterminal_cmd = 'ipython3'
let g:slime_vimterminal_config = {'term_finish': 'close'}

let g:slime_python_ipython = 1
let g:slime_cell_delimiter = "# %%"
let g:slime_dont_ask_default = 1
'''

[[plugins]]
repo = 'hanschen/vim-ipython-cell'
on_source = 'jupytext.vim'
