[[plugins]]
repo = 'lervag/vimtex'
on_ft=['tex']
hook_source='''
let g:vimtex_view_general_viewer = 'displayline'
let g:vimtex_view_general_options = '-r @line @pdf @tex'
'''

[[plugins]]
repo = 'skanehira/preview-markdown.vim'
on_ft=['markdown']
hook_source='''
let g:preview_markdown_auto_update = 1
let g:preview_markdown_parser = "glow"
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_ft='help'
hook_add = 'set helplang=ja'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
hook_add = '''
" let g:quickrun_config = {}
'''

[[plugins]]
repo = 'skanehira/denops-translate.vim'
on_cmd = 'Translate'

# [[plugins]]
# repo = 'cohama/lexima.vim'
# on_event = ['InsertEnter']

# [[plugins]]
# repo = 'vim-pandoc/vim-pandoc'
# on_ft = ['markdown']
