[[plugins]]
repo = 'itchyny/lightline.vim'
depends = 'iceberg.vim'
hook_add = '''
let g:lightline = {
\   'colorscheme': 'iceberg',
\ }
'''

[[plugins]]
repo = 'vim-jp/vital.vim'
merged = false

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
set background=dark
augroup vimrc
  autocmd ColorScheme * highlight Normal ctermbg=none
  autocmd ColorScheme * highlight NonText ctermbg=none
  autocmd ColorScheme * highlight LineNr ctermbg=none
  autocmd ColorScheme * highlight Folded ctermbg=none
  autocmd ColorScheme * highlight SignColumn ctermbg=none
  autocmd ColorScheme * highlight EndOfBuffer ctermbg=none
augroup END
colorscheme iceberg
'''

[[plugins]]
repo = 'vim-jp/syntax-vim-ex'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
let g:netrw_nogx = 1 " disable netrw's gx mapping.
nmap gx <Plug>(openbrowser-smart-search)
vmap gx <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'machakann/vim-sandwich'
