[[plugins]]
repo = 'lervag/vimtex'
on_ft=['tex']
hook_source='''
let g:vimtex_view_general_viewer = 'displayline'
let g:vimtex_view_general_options = '-r @line @pdf @tex'
'''

[[plugins]]
repo = 'skanehira/preview-markdown.vim'
on_ft=['md']
hook_source='''
let g:preview_markdown_auto_update = 1
let g:preview_markdown_parser = "glow"
'''

