[[plugins]]
repo = 'itchyny/lightline.vim'
depends = 'iceberg.vim'
hook_add = '''
let g:lightline = #{
\ colorscheme: 'iceberg',
\}
'''

[[plugins]]
repo = 'vim-jp/vital.vim'
merged = false

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'vim-jp/syntax-vim-ex'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
let g:netrw_nogx = 1 " disable netrw's gx mapping.
nmap gx <Plug>(openbrowser-smart-search)
vmap gx <Plug>(openbrowser-smart-search)
let g:openbrowser_browser_commands = [#{ name: 'w3m', args: ['wezterm', 'cli', 'spawn', '--', '{browser}', '{uri}'] }]
'''

[[plugins]]
repo = 'machakann/vim-sandwich'
