[[plugins]]
repo = 'vim-denops/denops.vim'
hook_add = '''
if $DENOPS_DEBUG
let g:denops#debug = 1
endif
'''

[[plugins]]
repo = 'tyru/capture.vim'
on_cmd = 'Capture'

[[plugins]]
repo = 'lervag/vimtex'
on_ft=['tex']
hook_add='''
let g:vimtex_view_method = 'skim'
let g:vimtex_view_general_viewer='/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options = '@line @pdf @tex'
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_ft='help'
hook_add = 'set helplang=ja'

# {{{ vim-quickrun

[[plugins]]
repo = 'lambdalisue/vim-quickrun-neovim-job'

[[plugins]]
repo = 'statiolake/vim-quickrun-runner-nvimterm'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
depends = ['vim-quickrun-neovim-job', 'vim-quickrun-runner-nvimterm']
hook_add = '''
let s:done = quickrun#outputter#null#new()

function s:done.finish(session) abort
  echo 'url saved.'
endfunction

let s:submit = quickrun#outputter#null#new()

function s:submit.finish(session) abort
  if confirm('All Test Passed. Are You Submit?', "&Yes\n&No", 2) == 1
    QuickRun procon/submit!
  endif
endfunction

let g:quickrun_config = {
\ '_': {
\   'runner': has('nvim') ? 'neovim_job' : 'job',
\ },
\ 'test': {
\ 'exec': ['cat %s', 'cat %S'],
\ 'tempfile': '%{tempname()}.txt',
\ },
\ 'procon/download': {
\   'exec': [
\     'sh -c "echo %a > %{expand("%:p:h:S")}/.contest_url"',
\     'rm -rf %{expand("%:p:h:S")}/test/',
\     'oj d -d %{expand("%:p:h:S")}/test/ %a',
\   ],
\   'outputter': s:done,
\ },
\ 'procon/browse': {
\   'exec': ['sh -c "open \$(cat %{expand("%:p:h:S")}/.contest_url)"'],
\   'outputter': 'null',
\ },
\ 'procon/exec': {
\   'exec': [
\     'g++ -std=gnu++17 -Wall -Wextra -DLOCAL -O2 %s -o %s:p:r',
\     '%s:p:r %a',
\   ],
\   'runner': has('nvim') ? 'nvimterm' : 'terminal',
\   'runner/nvimterm/opener': 'new',
\   'runner/nvimterm/into': 1,
\   'runner/terminal/into': 1,
\   'tempfile': '%{tempname()}.cpp',
\   'hook/sweep/files': ['%S:p:r'],
\ },
\ 'procon/test': {
\   'exec': [
\     'g++ -std=gnu++17 -Wall -Wextra -DLOCAL -O2 %s -o %s:p:r',
\     'oj test -N -c %s:p:r --tle 4 -d %{expand("%:p:h:S")}/test/'
\   ],
\   'tempfile': '%{tempname()}.cpp',
\   'hook/sweep/files': ['%S:p:r'],
\   'outputter/buffer/bufname': 'procon://test',
\   'outputter/buffer/filetype': 'procon',
\ },
\ 'procon/submit': {
\   'type': 'procon/test',
\   'outputter': 'error',
\   'outputter/success': s:submit,
\   'outputter/error': 'buffer',
\ },
\ 'procon/submit!': {
\   'exec': [
\     'sh -c "oj-bundle -I ~/Library/cpp-library %s | sed -e ''/#line/d'' > %s:p:r"',
\     'sh -c "oj submit -y --wait=0 -l 4003 \$(cat %{expand("%:p:h:S")}/.contest_url) %s:p:r"',
\   ],
\   'tempfile': '%{tempname()}.cpp',
\   'outputter': 'null',
\   'hook/sweep/files': ['%S:p:r'],
\ },
\ 'procon/generate': {
\   'exec': [
\     'cd %{expand("%:p:h:S")}',
\     'g++ -std=gnu++17 -Wall -Wextra -DLOCAL -O2 tle.cpp -o tle',
\     'oj g/i ./generate.py',
\     'oj g/o -c ./tle',
\   ],
\   'hook/sweep/files': ['%{expand("%:p:h:S")}/tle']
\ },
\ 'procon/hack': {
\   'exec': [
\     'cd %{expand("%:p:h:S")}',
\     'g++ -std=gnu++17 -Wall -Wextra -DLOCAL -O2 main.cpp -o program',
\     'g++ -std=gnu++17 -Wall -Wextra -DLOCAL -O2 tle.cpp -o tle',
\     'timeout 10 oj g/i -c ./tle --hack ./program ./generate.py',
\   ],
\   'hook/sweep/files': ['%{expand("%:p:h:S")}/program', '%{expand("%:p:h:S")}/tle']
\ },
\}

command! -nargs=1 ProconDownload QuickRun procon/download -args <args>
command! ProconBrowse QuickRun procon/browse
command! ProconExec QuickRun procon/exec
command! ProconTest QuickRun procon/test
command! -bang ProconSubmit QuickRun procon/submit<bang>
command! ProconGenerate QuickRun procon/generate
command! ProconHack QuickRun procon/hack
'''

# }}}

[[plugins]]
repo = 'yuki-yano/fuzzy-motion.vim'
on_cmd = 'FuzzyMotion'
hook_add = '''
nnoremap <Plug>(leader)<space> <cmd>FuzzyMotion<cr>
'''

[[plugins]]
repo = 'skanehira/denops-translate.vim'
on_cmd = 'Translate'

[[plugins]]
repo = 'skanehira/denops-silicon.vim'
on_cmd = 'Silicon'
hook_add = '''
let g:silicon_options = { 'font': 'Source Code Pro for Powerline', }
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'
hook_add = '''
let g:precious_enable_switchers = {
\ 'toml': { 'setfiletype': 0 },
\}
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_add = '''
let g:context_filetype#filetypes = {
\   'help': [
\     {
\       'start': '>$',
\       'end': '^\S',
\       'filetype': 'vim.help',
\     },
\   ],
\ }
'''

[[plugins]]
repo = 'lambdalisue/gin.vim'
depends = 'denops.vim'
on_cmd = ['Gin', 'GinBranch', 'GinChaperon', 'GinDiff', 'GinEdit', 'GinPatch', 'GinStatus']

[[plugins]]
repo = 'skanehira/denops-gh.vim'
depends = 'denops.vim'
on_path = ['https://github.com/*', 'gh://*']

[[plugins]]
repo = 'thinca/vim-qfreplace'
on_cmd = 'Qfreplace'

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = ['InsertEnter']
# rev = 'feature/feedkeys'
hook_source = '''
call lexima#add_rule({
\ 'char': '<CR>',
\ 'input': '<CR>',
\ 'input_after': '<CR>endsnippet',
\ 'at': 'snippet\>.*\%#$',
\ 'filetype': 'snippets',
\})

let s:lexima_cpp_rules = [
\ {'char': '@', 'at': 'all \(\w\+\)\%#', 'input': '\<C-W>\<C-W>\1.begin(), \1.end()', 'with_submatch': 1},
\ {'char': '@', 'at': 'rall \(\w\+\)\%#', 'input': '\<C-W>\<C-W>\1.rbegin(), \1.rend()', 'with_submatch': 1},
\ ]

for rule in s:lexima_cpp_rules
  let rule.filetype = 'cpp'
  call lexima#add_rule(rule)
endfor

let s:lexima_tex_rules = [
\ {'char': '[', 'at': '\\\%#', 'input': '[<CR>', 'input_after': '<CR>\]'},
\
\ {'char': '{', 'at': '\\\%#', 'input_after': '\}'},
\ {'char': '<BS>', 'at': '\\{\%#\\}', 'input': '<BS><BS>', 'delete': 2},
\
\ {'char': '(', 'at': '\\left\%#', 'input_after': '\right)'},
\ {'char': ')', 'at': '\%#\\right)', 'leave': 7},
\ {'char': '[', 'at': '\\left\%#', 'input_after': '\right]'},
\ {'char': ']', 'at': '\%#\\right]', 'leave': 7},
\ {'char': '{', 'at': '\\left\\\%#', 'input_after': '\right\}'},
\ {'char': '}', 'at': '\\\%#\\right\\}', 'input': '<BS>\right\}', 'delete': 8},
\
\ {'char': '$', 'input_after': '$'},
\ {'char': '$', 'at': '\\\%#'},
\ {'char': '$', 'at': '\%#\$', 'leave': 1},
\ {'char': '<BS>', 'at': '\$\%#\$', 'delete': 1},
\ {'char': '<CR>', 'at': '\$\%#\$', 'input_after': '<CR>'},
\]

for rule in s:lexima_tex_rules
  let rule.filetype = 'tex'
  call lexima#add_rule(rule)
endfor
'''

### pandoc
[[plugins]]
repo = 'vim-pandoc/vim-pandoc'
on_ft = ['markdown']
on_cmd = 'Pandoc'
hook_add = '''
let g:pandoc#filetypes#handled = ["pandoc", "markdown"]
let g:pandoc#filetypes#pandoc_markdown = 0
let g:pandoc#spell#enabled = 0
let g:pandoc#command#autoexec_on_writes = 0
'''

[[plugins]]
repo = 'vim-pandoc/vim-pandoc-syntax'
on_source = ['vim-pandoc']

### jupyter
[[plugins]]
repo = 'goerz/jupytext.vim'
on_path = '.*\.ipynb'
hook_add = '''
let g:jupytext_fmt = 'py:percent'
let g:jupytext_filetype_map = {'py': 'python'}
'''

[[plugins]]
repo = 'jpalardy/vim-slime'
on_source = 'jupytext.vim'
hook_add = '''
let g:slime_target = 'vimterminal'
let g:slime_vimterminal_cmd = 'ipython3'
let g:slime_vimterminal_config = {'term_finish': 'close'}

let g:slime_python_ipython = 1
let g:slime_cell_delimiter = "# %%"
let g:slime_dont_ask_default = 1
'''

[[plugins]]
repo = 'hanschen/vim-ipython-cell'
on_source = 'jupytext.vim'
