hook_add = '''
" LaTeX
let g:tex_flavor = 'latex'
let g:tex_conceal = ''

" Vim
let g:vim_indent_cont = 0

" Disable default plugins
let g:loaded_2html_plugin      = v:true
let g:loaded_logiPat           = v:true
let g:loaded_getscriptPlugin   = v:true
let g:loaded_gzip              = v:true
let g:loaded_gtags             = v:true
let g:loaded_gtags_cscope      = v:true
let g:loaded_man               = v:true
let g:loaded_matchit           = v:true
let g:loaded_matchparen        = v:true
let g:loaded_netrwFileHandlers = v:true
let g:loaded_netrwPlugin       = v:true
let g:loaded_netrwSettings     = v:true
let g:loaded_rrhelper          = v:true
let g:loaded_shada_plugin      = v:true
let g:loaded_spellfile_plugin  = v:true
let g:loaded_tarPlugin         = v:true
let g:loaded_tutor_mode_plugin = v:true
let g:loaded_vimballPlugin     = v:true
let g:loaded_zipPlugin         = v:true
'''

[ftplugin]

_ = '''
'''

cpp = '''
nnoremap <buffer> <silent> <LocalLeader>cc
\ <Cmd>call term_start(['make', 'run'], {
\ 'term_name': 'make-run',
\ 'term_rows': 10,
\ 'cwd': expand('%:p:h'),
\})<CR>
nnoremap <buffer> <silent> <LocalLeader>cl
\ <Cmd>%d<CR><Cmd>0r ~/.procon/cpp/main.cpp<CR>
'''

help = '''
setlocal iskeyword+=:,#,-,(,)
setlocal nofoldenable
setlocal tabstop=8
'''

make = '''
setlocal noexpandtab
'''

markdown_tex = '''
setlocal wrap
'''

snippets = '''
" let b:context_filetype_filetypes = {
"   \ 'snippets': [
"     \ {
"       \ 'start': '^snippet .*$',
"       \ 'end': '^endsnippet',
"       \ 'filetype': expand('%:t:r'),
"       \ }
"   \ ],
"   \ }
'''

tex = '''
iunmap <buffer>]]
'''

vim = '''
setlocal tabstop=2
setlocal shiftwidth=2
setlocal expandtab
'''
