[[plugins]]
repo = 'Shougo/pum.vim'
hook_source = '''
call pum#set_option(#{
\ preview: v:true,
\ preview_height: 100,
\ preview_width: 80,
\})
'''

[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = ['InsertEnter', 'CmdlineEnter', 'CursorHold']
depends = ['denops.vim', 'pum.vim']
hooks_file = '$VIM_DPP/ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
on_source = 'ddc.vim'
depends = 'pum.vim'

[[plugins]]
repo = 'Shougo/ddc-source-lsp'
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-buffer'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-vim'
on_source = 'ddc.vim'

[[plugins]]
repo = 'uga-rosa/ddc-source-nvim-lua'
on_source = 'ddc.vim'

[[plugins]]
repo = 'uga-rosa/denippet.vim'
on_source = 'ddc.vim'
hook_add = '''
imap <C-l> <Plug>(denippet-expand-or-jump)
smap <C-l> <Plug>(denippet-jump-next)
imap <C-n> <Plug>(denippet-choice-next)
'''
hook_source = '''
for s:snip in globpath($VIM_DIR, 'snippets/*', 1, 1)
  call denippet#load(s:snip)
endfor
'''

[[plugins]]
repo = 'Shougo/ddc-source-cmdline'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline-history'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-shell-native'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-copilot'
on_source = 'ddc.vim'

# Install your filters
[[plugins]]
repo = 'tani/ddc-fuzzy'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-converter_remove_overlap'
on_source = 'ddc.vim'
