hooks_file = '$VIM_DPP/filetype.vim'

# {{{ dpp.vim
[[plugins]]
repo = 'Shougo/dpp.vim'

[[plugins]]
repo = 'Shougo/dpp-ext-lazy'

[[plugins]]
repo = 'Shougo/dpp-ext-toml'

[[plugins]]
repo = 'Shougo/dpp-ext-local'

[[plugins]]
repo = 'Shougo/dpp-ext-installer'
hook_add = '''
command DppInstall call dpp#async_ext_action('installer', 'install')
command DppUpdate call dpp#async_ext_action('installer', 'update')
'''

[[plugins]]
repo = 'Shougo/dpp-protocol-git'
# }}}

[[plugins]]
repo = 'EdenEast/nightfox.nvim'
lua_add = '''
require('nightfox').setup({
  options = {
    transparent = true,
  },
  groups = {
    all = {
      StatusLine = { link = "WinSeparator", },
      StatusLineNC = { link = "WinSeparator", },
      ColorColumn = { bg = "palette.bg3" },
    },
  },
})
vim.opt.background = "dark"
vim.cmd.colorscheme('carbonfox')
'''

[[plugins]]
repo = 'andymass/vim-matchup'

[[plugins]]
repo = 'machakann/vim-sandwich'
hook_add = '''
nnoremap s <Nop>
xnoremap s <Nop>
'''

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-entire'
depends = 'vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-line'
depends = 'vim-textobj-user'

[[plugins]]
repo = 'machakann/vim-textobj-functioncall'
depends = 'vim-textobj-user'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'yuki-yano/vim-operator-replace'
depends = 'vim-operator-user'
hook_add = '''
nmap _ <Plug>(operator-replace)
xmap _ <Plug>(operator-replace)
omap _ <Plug>(operator-replace)
'''

[[plugins]]
repo = 'vim-denops/denops.vim'
hook_add = '''
let g:denops#server#deno_args = ['-q', '--no-lock', '--unstable-kv', '--unstable-ffi', '-A']
"let g:denops_server_addr = '127.0.0.1:32123'
if $DENOPS_DEBUG
let g:denops#debug = 1
endif
'''

[[plugins]]
repo = 'lambdalisue/vim-guise'

[[plugins]]
repo = 'lambdalisue/vim-suda'
hook_add = '''
let g:suda_smart_edit = 1
'''

[[plugins]]
repo = 'Shougo/shougo-s-github'
if = false
