[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_add = '''
let g:vimtex_view_method = 'zathura_simple'
let g:vimtex_syntax_enabled = 0
let g:vimtex_syntax_conceal_disable = 1
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'
hook_add = 'set helplang=ja'

[[plugins]]
repo = 'haya14busa/vim-asterisk'
on_map = ['<Plug>(asterisk-']
hook_add = '''
noremap * <Plug>(asterisk-z*)
noremap # <Plug>(asterisk-z#)
noremap g* <Plug>(asterisk-gz*)
noremap g# <Plug>(asterisk-gz#)
'''

[[plugins]]
repo = 'thinca/vim-qfreplace'
on_cmd = 'Qfreplace'

[[plugins]]
repo = 'itchyny/vim-qfedit'
on_event = 'QuickFixCmdPre'

[[plugins]]
repo = 'lambdalisue/vim-quickrun-neovim-job'

[[plugins]]
repo = 'statiolake/vim-quickrun-runner-nvimterm'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
depends = ['vim-quickrun-neovim-job', 'vim-quickrun-runner-nvimterm']
hook_add = '''
let g:quickrun_config = {
\ '_': {
\   'runner': 'neovim_job',
\ },
\}
'''

[[plugins]]
repo = 'Shougo/ddt.vim'
hooks_file = '$VIM_DPP/ddt.vim'

[[plugins]]
repo = 'Shougo/ddt-ui-terminal'
on_source = 'ddt.vim'

[[plugins]]
repo = 'Shougo/ddt-ui-shell'
on_source = 'ddt.vim'

[[plugins]]
repo = 'tani/dmacro.vim'
on_event = ['InsertEnter', 'CursorHold', 'BufRead']
hook_source = '''
inoremap <C-@> <Plug>(dmacro-play-macro)
nnoremap <C-@> <Plug>(dmacro-play-macro)
'''

[[plugins]]
repo = 'skanehira/denops-translate.vim'
on_cmd = 'Translate'

[[plugins]]
repo = 'vim-skk/skkeleton'
on_map = { ict = ['<Plug>(skkeleton-'] }
hooks_file = '$VIM_DPP/skkeleton.vim'

[[plugins]]
name = 'skk-dict'
if = false

[[plugins]]
repo = 'tani/vim-glance'
on_cmd = 'Glance'
hook_add = '''
let g:glance#stylesheet = [
\ '@import url("https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css");',
\ '@import url("https://cdn.jsdelivr.net/npm/water.css@2/out/light.css");',
\]->join("\n")
let g:glance#config = '$VIM_DPP/glance.ts'->expand()
'''
