[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_add = '''
if has('mac')
  let g:vimtex_view_method = 'skim'
  let g:vimtex_view_general_viewer='/Applications/Skim.app/Contents/SharedSupport/displayline'
  let g:vimtex_view_general_options = '@line @pdf @tex'
endif
if has('nvim')
  let g:vimtex_syntax_enabled = 0
  let g:vimtex_syntax_conceal_disable = 1
endif
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'
hook_add = 'set helplang=ja'

[[plugins]]
repo = 'haya14busa/vim-asterisk'
on_map = ['<Plug>(asterisk-']
hook_add = '''
noremap * <Plug>(asterisk-z*)
noremap # <Plug>(asterisk-z#)
noremap g* <Plug>(asterisk-gz*)
noremap g# <Plug>(asterisk-gz#)
'''

[[plugins]]
repo = 'thinca/vim-qfreplace'
on_cmd = 'Qfreplace'

[[plugins]]
repo = 'itchyny/vim-qfedit'
on_event = 'QuickFixCmdPre'

[[plugins]]
repo = 'tyru/capture.vim'
on_cmd = 'Capture'

[[plugins]]
repo = 'lambdalisue/vim-quickrun-neovim-job'

[[plugins]]
repo = 'statiolake/vim-quickrun-runner-nvimterm'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
depends = ['vim-quickrun-neovim-job', 'vim-quickrun-runner-nvimterm']
hook_add = '''
let g:quickrun_config = {
\ '_': {
\   'runner': 'neovim_job',
\ },
\}
'''

[[plugins]]
repo = 'Shougo/deol.nvim'
hooks_file = '$VIM_DPP/deol.vim'

[[plugins]]
repo = 'Bakudankun/BackAndForward.vim'
on_map = ['<Plug>(backandforward-']
hook_add = '''
let g:backandforward_config = #{
\ auto_map: 0,
\ define_commands: 0,
\}
nnoremap g<C-o> <Plug>(backandforward-back)
nnoremap g<C-i> <Plug>(backandforward-forward)
'''

[[plugins]]
repo = 'tani/dmacro.vim'
on_event = ['InsertEnter', 'CursorHold', 'BufRead']
hook_source = '''
inoremap <C-@> <Plug>(dmacro-play-macro)
nnoremap <C-@> <Plug>(dmacro-play-macro)
'''

[[plugins]]
repo = 'skanehira/denops-translate.vim'
on_cmd = 'Translate'

[[plugins]]
repo = 'lambdalisue/vim-gin'
on_cmd = [
  'Gin',
  'GinBranch',
  'GinBrowse',
  'GinBuffer',
  'GinCd',
  'GinChaperon',
  'GinDiff',
  'GinEdit',
  'GinLcd',
  'GinLog',
  'GinPatch',
  'GinStatus',
  'GinTcd',
]
hooks_file = '$VIM_DPP/gin.vim'

[[plugins]]
repo = 'vim-skk/skkeleton'
on_map = { ict = ['<Plug>(skkeleton-'] }
hooks_file = '$VIM_DPP/skkeleton.vim'

[[plugins]]
repo = 'skk-dev/dict'
name = 'skk-dict'
if = false

[[plugins]]
repo = 'tani/vim-glance'
on_cmd = 'Glance'
hook_add = '''
let g:glance#stylesheet = [
\ '@import url("https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css");',
\ '@import url("https://cdn.jsdelivr.net/npm/water.css@2/out/light.css");',
\]->join("\n")
let g:glance#config = '$VIM_DPP/glance.ts'->expand()
'''
