[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = ['BufRead', 'CursorHold']
hook_post_update = 'TSUpdate'
lua_source = '''
require'nvim-treesitter.configs'.setup {
    ensure_installed = 'all',
    highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
    },
}
'''

[[plugins]]
repo = 'nvim-treesitter/playground'
on_cmd = ['TSPlaygroundToggle', 'TSHighlightCapturesUnderCursor']

[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'williamboman/mason.nvim'
on_cmd = 'Mason'
lua_source = '''
require'mason'.setup{}
'''

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
on_source = 'ddc-source-nvim-lsp'
depends = ['mason.nvim', 'nvim-lspconfig']
lua_source = '''
vim.cmd [[set signcolumn=yes]]
local nvim_lsp = require'lspconfig'
nvim_lsp.clangd.setup{}
nvim_lsp.denols.setup{}
-- nvim_lsp.deno.setup{}
require'mason-lspconfig'.setup_handlers {
    function(server_name)
        nvim_lsp[server_name].setup{}
    end
}
'''

[[plugins]]
repo = 'Shougo/ddc-source-nvim-lsp'
depends = 'mason-lspconfig.nvim'
on_source = 'ddc.vim'
