[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = ['BufRead', 'CursorHold']
hook_post_update = 'TSUpdate'
lua_source = '''
require'nvim-treesitter.configs'.setup {
    ensure_installed = 'all',
    highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
    },
}
'''

[[plugins]]
repo = 'nvim-treesitter/playground'
on_cmd = ['TSPlaygroundToggle', 'TSHighlightCapturesUnderCursor']

[[plugins]]
repo = 'neovim/nvim-lspconfig'
lua_source = '''
local nvim_lsp = require'lspconfig'
local on_attach = function(client, bufnr)
    vim.fn.setbufvar(bufnr, "&signcolumn", "yes")
    local bufopts = { noremap = true, silent = true, buffer = bufnr }
    vim.keymap.set("n", "K", vim.lsp.buf.hover, bufopts)
    vim.keymap.set("n", "<Plug>(leader)ge", vim.diagnostic.open_float, bufopts)
    vim.keymap.set("n", "<Plug>(leader)rn", vim.lsp.buf.rename, bufopts)
    vim.keymap.set("n", "<Plug>(leader)ca", vim.lsp.buf.code_action, bufopts)
end
nvim_lsp.clangd.setup {
    on_attach = on_attach,
}
nvim_lsp.denols.setup {
    on_attach = on_attach,
}
nvim_lsp.texlab.setup {
    on_attach = on_attach,
}
nvim_lsp.rust_analyzer.setup {
    on_attach = on_attach,
}
'''

[[plugins]]
repo = 'Shougo/ddc-source-nvim-lsp'
depends = 'nvim-lspconfig'
on_source = 'ddc.vim'
