[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
let g:lsp_diagnostics_echo_cursor = 1
let g:lsp_inlay_hints_enabled = has('nvim')
let g:lsp_inlay_hints_mode = {
\ 'normal': ['curline'],
\}
let g:lsp_log_file = expand('~/vim-lsp.log')

if executable('wolframscript')
  autocmd User lsp_setup call lsp#register_server(#{
  \ name: 'lsp-wl',
  \ tcp: {server_info -> '127.0.0.1:6536'},
  \ allowlist: ['wolframscript'],
  \})
endif

autocmd vimrc BufEnter *.wls set filetype=wolframscript

function! s:on_lsp_buffer_enabled() abort
  setlocal signcolumn=yes
  nmap <buffer> <Plug>(leader)rn <plug>(lsp-rename)
  nmap <buffer> <Plug>(leader)ca <plug>(lsp-code-action)
  nmap <buffer> K <plug>(lsp-hover)
endfunction

augroup lsp_install
  au!
  " call s:on_lsp_buffer_enabled only for languages that has the server registered.
  autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END
'''
hook_post_source = 'call lsp#enable()'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = 'vim-lsp'
on_source = 'vim-lsp'

[[plugins]]
repo = 'shun/ddc-vim-lsp'
depends = ['ddc.vim', 'vim-lsp']
on_source = 'ddc.vim'

[[plugins]]
repo = 'mattn/vim-notification'

