# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cargo-compete = {
    pname = "cargo-compete";
    version = "v0.10.7";
    src = fetchFromGitHub {
      owner = "qryxip";
      repo = "cargo-compete";
      rev = "v0.10.7";
      fetchSubmodules = false;
      sha256 = "sha256-qlRVHSUVOqdTx4H3pE19Fy634742veTisHm6IqfKBUQ=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./cargo-compete-v0.10.7/Cargo.lock;
      outputHashes = {

      };
    };
  };
  cargo-equip = {
    pname = "cargo-equip";
    version = "v0.20.1";
    src = fetchFromGitHub {
      owner = "qryxip";
      repo = "cargo-equip";
      rev = "v0.20.1";
      fetchSubmodules = false;
      sha256 = "sha256-yxRiG96jC7zdlMQpL0B9Mle2kD1TOhqTZzMX3I8IE9I=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./cargo-equip-v0.20.1/Cargo.lock;
      outputHashes = {

      };
    };
  };
  moralerspace-nf = {
    pname = "moralerspace-nf";
    version = "1.0.2";
    src = fetchurl {
      url = "https://github.com/yuru7/moralerspace/releases/download/v1.0.2/MoralerspaceNF_v1.0.2.zip";
      sha256 = "sha256-BtvY8r3VJZ0H5D6f1WAfamL4CmmBPKsYAcnp3Emccc4=";
    };
  };
  online-judge-verify-helper = {
    pname = "online-judge-verify-helper";
    version = "adbff121b1f96de5f34e9f1483eb47d661c54075";
    src = fetchFromGitHub {
      owner = "online-judge-tools";
      repo = "verification-helper";
      rev = "adbff121b1f96de5f34e9f1483eb47d661c54075";
      fetchSubmodules = false;
      sha256 = "sha256-f7Ge8kLRQv9uxdNGtgNsypGVY0XAnKPCg8HYQ5nT6mI=";
    };
    date = "2024-10-09";
  };
  tree-sitter-satysfi = {
    pname = "tree-sitter-satysfi";
    version = "5519c547418ecb31ac7d63e64653aed726b5d1c3";
    src = fetchFromGitHub {
      owner = "monaqa";
      repo = "tree-sitter-satysfi";
      rev = "5519c547418ecb31ac7d63e64653aed726b5d1c3";
      fetchSubmodules = false;
      sha256 = "sha256-yei8UHiVChYpx2UyPsDyOd3usItZN68rwu0+VoBtPi0=";
    };
    date = "2023-04-09";
  };
  vivaldi-ffmpeg-codecs = {
    pname = "vivaldi-ffmpeg-codecs";
    version = "126.0.6478.126";
    src = fetchurl {
      url = "https://api.snapcraft.io/api/v1/snaps/download/XKEcBqPM06H1Z7zGOdG5fbICuf8NWK5R_2899.snap";
      sha256 = "sha256-pBFKnW1zcthqyUhMG4DN/tVcSo41HTliuRYOscWTEwY=";
    };
  };
}
