# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cargo-compete = {
    pname = "cargo-compete";
    version = "v0.10.7";
    src = fetchFromGitHub {
      owner = "qryxip";
      repo = "cargo-compete";
      rev = "v0.10.7";
      fetchSubmodules = false;
      sha256 = "sha256-qlRVHSUVOqdTx4H3pE19Fy634742veTisHm6IqfKBUQ=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./cargo-compete-v0.10.7/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  cargo-equip = {
    pname = "cargo-equip";
    version = "v0.20.1";
    src = fetchFromGitHub {
      owner = "qryxip";
      repo = "cargo-equip";
      rev = "v0.20.1";
      fetchSubmodules = false;
      sha256 = "sha256-yxRiG96jC7zdlMQpL0B9Mle2kD1TOhqTZzMX3I8IE9I=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./cargo-equip-v0.20.1/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  cargo-executable-payload = {
    pname = "cargo-executable-payload";
    version = "v0.2.0";
    src = fetchFromGitHub {
      owner = "qryxip";
      repo = "cargo-executable-payload";
      rev = "v0.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-eb/5K65Tavtm2w6QqAM5hSSrLL5LiCcDGw3u+HwRiMs=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./cargo-executable-payload-v0.2.0/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  janome = {
    pname = "janome";
    version = "0.5.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/J/Janome/Janome-0.5.0.tar.gz";
      sha256 = "sha256-zko+16RjXC+AE5Y5Mn1bHgOBhYrXSjxKYejMg/ggQA4=";
    };
  };
  moralerspace-nf = {
    pname = "moralerspace-nf";
    version = "1.0.2";
    src = fetchurl {
      url = "https://github.com/yuru7/moralerspace/releases/download/v1.0.2/MoralerspaceNF_v1.0.2.zip";
      sha256 = "sha256-BtvY8r3VJZ0H5D6f1WAfamL4CmmBPKsYAcnp3Emccc4=";
    };
  };
  online-judge-verify-helper = {
    pname = "online-judge-verify-helper";
    version = "adbff121b1f96de5f34e9f1483eb47d661c54075";
    src = fetchFromGitHub {
      owner = "online-judge-tools";
      repo = "verification-helper";
      rev = "adbff121b1f96de5f34e9f1483eb47d661c54075";
      fetchSubmodules = false;
      sha256 = "sha256-f7Ge8kLRQv9uxdNGtgNsypGVY0XAnKPCg8HYQ5nT6mI=";
    };
    date = "2024-10-09";
  };
  ssss = {
    pname = "ssss";
    version = "239926f8b53af2a59dbf1566f786b83de8fad410";
    src = fetchFromGitHub {
      owner = "vm-xeck";
      repo = "ssss";
      rev = "239926f8b53af2a59dbf1566f786b83de8fad410";
      fetchSubmodules = false;
      sha256 = "sha256-3oRph/iio6O2BJ4+9cY0zpyUek0Tknm1874AFLe7K9Q=";
    };
    date = "2024-09-19";
  };
  vivaldi-ffmpeg-codecs = {
    pname = "vivaldi-ffmpeg-codecs";
    version = "126.0.6478.126";
    src = fetchurl {
      url = "https://api.snapcraft.io/api/v1/snaps/download/XKEcBqPM06H1Z7zGOdG5fbICuf8NWK5R_2899.snap";
      sha256 = "sha256-pBFKnW1zcthqyUhMG4DN/tVcSo41HTliuRYOscWTEwY=";
    };
  };
  vlgothic = {
    pname = "vlgothic";
    version = "20230918";
    src = fetchFromGitHub {
      owner = "daisukesuzuki";
      repo = "VLGothic";
      rev = "20230918";
      fetchSubmodules = false;
      sha256 = "sha256-X4HbFxJCzoU+QP/P328fB7BiHJZCiJmuJ1Mh2MrOZlw=";
    };
  };
}
