command! CampOpen call camp#open()
command! CampRun call camp#run()
command! CampTest call camp#test()
command! -bang CampSubmit call camp#submit(<bang>0)
command! CampSummaries call camp#summaries()
