[[plugins]]
repo = 'Shougo/pum.vim'
hook_add = '''
call pum#set_option(#{
\ preview: v:true,
\})
'''

[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim', 'pum.vim']
hooks_file = '$VIM_HOOKS/ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
depends = 'pum.vim'

[[plugins]]
repo = 'shun/ddc-vim-lsp'

[[plugins]]
repo = 'Shougo/ddc-source-nvim-lsp'

[[plugins]]
repo = 'matsui54/denops-signature_help'
depends = 'denops.vim'
hook_add = '''
call signature_help#enable()
let g:lsp_signature_help_enabled = 0
'''

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
depends = 'denops.vim'
hook_add = '''
call popup_preview#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-source-mocword'

[[plugins]]
repo = 'Shougo/ddc-source-around'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'uga-rosa/ddc-source-nvim-lua'

[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = '''
let g:UltiSnipsEditSplit = 'horizontal'
let g:UltiSnipsExpandTrigger = '<C-l>'
let g:UltiSnipsJumpForwardTrigger = '<C-l>'
let g:UltiSnipsJumpBackwardTrigger = '<C-p>'
'''

[[plugins]]
repo = 'matsui54/ddc-ultisnips'
depends = ['ddc.vim', 'ultisnips']

[[plugins]]
repo = 'Shougo/ddc-source-cmdline'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline-history'

[[plugins]]
repo = 'Shougo/ddc-source-shell-native'

[[plugins]]
repo = 'vim-skk/skkeleton'
depends = 'denops.vim'
hooks_file = '$VIM_HOOKS/skkeleton.vim'

# Install your filters
[[plugins]]
repo = 'tani/ddc-fuzzy'
