[[plugins]]
repo = 'Shougo/ddu.vim'
depends = ['denops.vim']
hooks_file = '$VIM_HOOKS/ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
depends = 'ddu.vim'

# UI
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
hooks_file = '$VIM_HOOKS/ddu-ui-ff.vim'

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
hooks_file = '$VIM_HOOKS/ddu-ui-filer.vim'

# sources
[[plugins]]
repo = 'Shougo/ddu-source-action'

[[plugins]]
repo = 'Shougo/ddu-source-file'
depends = 'ddu-kind-file'

[[plugins]]
repo = 'shun/ddu-source-buffer'

[[plugins]]
repo = 'kuuote/ddu-source-mr'
depends = 'mr.vim'

[[plugins]]
repo = 'lambdalisue/mr.vim'
hook_add = '''
let g:mr#mru#predicates = [
\ { filename -> filename !~# '/doc/' },
\ { filename -> filename !~# '/.git/' },
\]
'''

[[plugins]]
repo = 'matsui54/ddu-source-help'

[[plugins]]
repo = 'Shougo/ddu-source-file_point'

[[plugins]]
repo = 'uga-rosa/ddu-source-lsp'

[[plugins]]
repo = '4513ECHO/ddu-source-emoji'

[[plugins]]
repo = 'Shougo/ddu-source-vim'

#filters
[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo = 'kyoh86/ddu-filter-converter_hl_dir'

#kinds
[[plugins]]
repo = 'Shougo/ddu-kind-file'

[[plugins]]
repo = 'Shougo/ddu-kind-word'

#columns
[[plugins]]
repo = 'Shougo/ddu-column-filename'
