[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = #{
\ colorscheme: 'carbonfox',
\ active: #{
\   left: [ [ 'mode', 'paste', 'skk_mode' ],
\             [ 'readonly', 'filename', 'modified' ] ]
\   },
\ component_function: #{
\   skk_mode: 'g:lightline_skk#mode',
\   },
\}
'''

[[plugins]]
repo = 'yasunori-kirin0418/lightline_skk.vim'
on_source = 'skkeleton'

[[plugins]]
repo = 'vim-jp/vital.vim'
merged = false

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'EdenEast/nightfox.nvim'
lua_add = '''
require('nightfox').setup({
  options = {
    transparent = true,
  }
})
'''

[[plugins]]
repo = 'vm-xeck/retskelet-nvim'

[[plugins]]
repo = 'vim-jp/syntax-vim-ex'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
let g:netrw_nogx = 1 " disable netrw's gx mapping.
nmap gx <Plug>(openbrowser-smart-search)
vmap gx <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'andymass/vim-matchup'

# {{{ textobj and operator
[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-entire'
depends = 'vim-textobj-user'
on_map = '<Plug>(textobj-entire-'

[[plugins]]
repo = 'kana/vim-textobj-line'
depends = 'vim-textobj-user'
on_map = '<Plug>(textobj-line-'

[[plugins]]
repo = 'machakann/vim-textobj-functioncall'
depends = 'vim-textobj-user'
on_map = '<Plug>(textobj-functioncall-'

[[plugins]]
repo = 'kana/vim-operator-user'
# }}}

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'vim-denops/denops.vim'
hook_add = '''
if $DENOPS_DEBUG
let g:denops#debug = 1
endif
'''

[[plugins]]
repo = 'lambdalisue/guise.vim'
depends = 'denops.vim'

[[plugins]]
repo = 'Shougo/shougo-s-github'
if = false

[[plugins]]
repo = 'rcarriga/nvim-notify'
if = 'has("nvim")'
lua_add = '''
vim.notify = function(...)
  vim.notify = require'notify'
  vim.notify.setup {
    background_colour = '#000000'
  }
  vim.notify(...)
end
'''
