hooks_file = '$VIM_HOOKS/filetype.vim'

# {{{ dpp.vim
[[plugins]]
repo = 'Shougo/dpp.vim'

[[plugins]]
repo = 'Shougo/dpp-ext-lazy'

[[plugins]]
repo = 'Shougo/dpp-ext-toml'

[[plugins]]
repo = 'Shougo/dpp-ext-installer'

[[plugins]]
repo = 'Shougo/dpp-protocol-git'
# }}}

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = #{
\ colorscheme: 'carbonfox',
\ active: #{
\   left: [['mode'], ['readonly', 'filename', 'modified']],
\   right: [['lineinfo'], ['filetype']],
\ },
\ tabline: #{ right: [[]] },
\}
'''

[[plugins]]
repo = 'vim-jp/vital.vim'
merged = false

[[plugins]]
repo = 'EdenEast/nightfox.nvim'
lua_add = '''
require('nightfox').setup({
  options = {
    transparent = true,
  }
})
'''

[[plugins]]
repo = 'vim-jp/syntax-vim-ex'

[[plugins]]
repo = 'andymass/vim-matchup'

[[plugins]]
repo = 'machakann/vim-sandwich'
hook_add = '''
nnoremap s <Nop>
xnoremap s <Nop>
'''

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-entire'
depends = 'vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-line'
depends = 'vim-textobj-user'

[[plugins]]
repo = 'machakann/vim-textobj-functioncall'
depends = 'vim-textobj-user'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'yuki-yano/vim-operator-replace'
depends = 'vim-operator-user'
hook_add = '''
nmap _ <Plug>(operator-replace)
xmap _ <Plug>(operator-replace)
omap _ <Plug>(operator-replace)
'''

[[plugins]]
repo = 'vim-denops/denops.vim'
hook_add = '''
let g:denops#deno = '~/.deno/bin/deno'->expand()
if $DENOPS_DEBUG
let g:denops#debug = 1
endif
'''

[[plugins]]
repo = 'lambdalisue/guise.vim'

[[plugins]]
repo = 'Shougo/shougo-s-github'
if = false
