[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = ['BufRead', 'CursorHold']
hook_post_update = 'TSUpdate'
lua_source = '''
local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
parser_config.satysfi = {
  install_info = {
    url = "https://github.com/monaqa/tree-sitter-satysfi", -- local path or git repo
    files = {"src/parser.c", "src/scanner.c"}
  },
  filetype = "satysfi", -- if filetype does not agrees with parser name
}

require'nvim-treesitter.configs'.setup {
    ensure_installed = 'all',
    highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
    },
    yati = {
        enable = true,
        default_lazy = true,
        default_fallback = "auto",
    },
    indent = {
        enable = false
    }
}
'''

[[plugins]]
repo = 'yioneko/nvim-yati'
depends = 'nvim-treesitter'

[[plugins]]
repo = 'nvim-treesitter/playground'
on_cmd = ['TSPlaygroundToggle', 'TSHighlightCapturesUnderCursor']

[[plugins]]
repo = 'neovim/nvim-lspconfig'
lua_source = '''
local lspconfig = require'lspconfig'
vim.api.nvim_create_autocmd('LspAttach', {
    group = vim.api.nvim_create_augroup('UserLspConfig', {}),
    callback = function(ev)
        local bufopts = { noremap = true, silent = true, buffer = ev.buf }
        vim.keymap.set("n", "K", vim.lsp.buf.hover, bufopts)
        vim.keymap.set("n", "<Plug>(leader)e", vim.diagnostic.open_float, bufopts)
        vim.keymap.set("n", "<Plug>(leader)f", vim.lsp.buf.format, bufopts)
        vim.keymap.set("n", "<Plug>(leader)rn", vim.lsp.buf.rename, bufopts)
    end
})
local config = {
  capabilities = require"ddc_nvim_lsp".make_client_capabilities(),
}
lspconfig.clangd.setup(config)
lspconfig.denols.setup(config)
lspconfig.texlab.setup(config)
lspconfig.rust_analyzer.setup(config)
local configs = require 'lspconfig.configs'
if not configs.satysfi_ls then
    configs.satysfi_ls = {
        default_config = {
            cmd = { 'satysfi-language-server' },
            filetypes = { 'satysfi' },
            root_dir = lspconfig.util.root_pattern('.git'),
            settings = {},
        },
    }
end
lspconfig.satysfi_ls.setup {}
'''

[[plugins]]
repo = 'Shougo/ddc-source-nvim-lsp'
depends = 'nvim-lspconfig'
on_source = 'ddc.vim'

[[plugins]]
repo = 'David-Kunz/treesitter-unit'
on_lua = 'treesitter-unit'
lua_add = '''
vim.api.nvim_set_keymap('x', 'iu', ':lua require"treesitter-unit".select()<CR>', {noremap=true})
vim.api.nvim_set_keymap('x', 'au', ':lua require"treesitter-unit".select(true)<CR>', {noremap=true})
vim.api.nvim_set_keymap('o', 'iu', ':<C-u>lua require"treesitter-unit".select()<CR>', {noremap=true})
vim.api.nvim_set_keymap('o', 'au', ':<C-u>lua require"treesitter-unit".select(true)<CR>', {noremap=true})
'''
