# Default colors
[colors.primary]
foreground = '#FFFFFF'
background = '#242424'

# Normal colors
[colors.normal]
black =   '#242424'
red =     '#F62B5A'
green =   '#47B413'
yellow =  '#E3C401'
blue =    '#24ACD4'
magenta = '#F2AFFD'
cyan =    '#13C299'
white =   '#E6E6E6'

# Bright colors
[colors.bright]
black =   '#616161'
red =     '#FF4D51'
green =   '#35D450'
yellow =  '#E9E836'
blue =    '#5DC5F8'
magenta = '#FEABF2'
cyan =    '#24DFC4'
white =   '#FFFFFF'
