name: check

on: [push]

jobs:
  install:
    strategy:
      matrix:
        runner:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: clone
        run: git clone https://github.com/qitoy/dotfiles.git ~/dotfiles
      - name: set symlink
        run: ~/dotfiles/mklink.sh
