name: check

on: [push]

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: install
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/qitoy/dotfiles/main/install.sh)"
