name: check

on: [push]

jobs:
  install:
    strategy:
      matrix:
        runner:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: install
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/qitoy/dotfiles/linux/install.sh)"
