name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: make vim/plugins
        run: |
          echo "# 使用Vimプラグイン一覧" > ./public/vim/plugins.md
          grep -E "repo = '[^/]+/[^/]+'" ./vim/tomls/*.toml | sed -e "s_.* '\(.*\)'_- [\1](https://github.com/\1)_" | sort >> ./public/vim/plugins.md
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          enable_jekyll: true
